# numpy - Numerical Python-used for creating nd-array

In [2]:
import numpy as np

# creating 1-D array

In [4]:
array1 = np.array([1,2,3,4,5,6])
print(array1)

[1 2 3 4 5 6]


In [6]:
array2 = np.array([i for i in range(1,101)])
array2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [8]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
np.random.randint(1,10,5)

array([2, 8, 8, 2, 1])

In [25]:
np.random.random([2,2])

array([[0.00146674, 0.54612502],
       [0.04132166, 0.33288392]])

In [27]:
np.random.rand(2,2)

array([[0.3798225 , 0.24469985],
       [0.07591574, 0.50844462]])

In [31]:
np.random.random([2,2,4,3,4,3,3,2,4])

array([[[[[[[[[3.35152536e-01, 3.76830775e-01, 5.42976912e-01,
               3.84512768e-01],
              [8.77799546e-01, 4.01275624e-01, 4.69394979e-01,
               5.55028229e-01]],

             [[7.19181290e-01, 3.17753603e-01, 6.40262388e-01,
               2.38475692e-01],
              [3.43684292e-01, 3.49736730e-01, 5.22427621e-01,
               8.50410433e-01]],

             [[1.48951517e-01, 9.83664560e-01, 9.39296739e-01,
               3.76614243e-01],
              [8.32276784e-01, 2.53619791e-01, 7.32988580e-01,
               4.64411107e-01]]],


            [[[6.38585360e-01, 4.71902605e-01, 1.10555094e-01,
               7.33341751e-02],
              [8.28753902e-01, 4.94505428e-01, 8.04608099e-01,
               1.48262204e-01]],

             [[7.02946119e-01, 4.56220518e-01, 5.21512240e-01,
               2.97129943e-01],
              [1.09781247e-01, 8.52066120e-02, 2.72750233e-01,
               8.17234596e-01]],

             [[3.37565696e-01, 4.46445

In [32]:
np.random.rand(2,2,1,3,4,5)

array([[[[[[0.92621172, 0.7395023 , 0.1105034 , 0.8219283 ,
            0.15659741],
           [0.57778763, 0.39032313, 0.4717055 , 0.67635163,
            0.41828595],
           [0.63398025, 0.68640321, 0.65800535, 0.43730319,
            0.01592772],
           [0.6098426 , 0.341175  , 0.05360753, 0.2883006 ,
            0.62285475]],

          [[0.12758963, 0.38367026, 0.849265  , 0.41607094,
            0.19088925],
           [0.43487914, 0.67264037, 0.711509  , 0.81243499,
            0.91991322],
           [0.29546692, 0.28483694, 0.62085948, 0.92093954,
            0.75798728],
           [0.71729087, 0.67024052, 0.79701024, 0.89248887,
            0.10034697]],

          [[0.5018496 , 0.94845515, 0.28475677, 0.30040451,
            0.66286808],
           [0.9828976 , 0.2214081 , 0.7110082 , 0.46010267,
            0.97437268],
           [0.0982196 , 0.45040861, 0.30254651, 0.31556474,
            0.9179006 ],
           [0.52806592, 0.08875893, 0.94977259, 0.72927756,
 

In [46]:
np.random.seed(1)#used yo fix the random generated values
np.random.random([2,2,2])

array([[[4.17022005e-01, 7.20324493e-01],
        [1.14374817e-04, 3.02332573e-01]],

       [[1.46755891e-01, 9.23385948e-02],
        [1.86260211e-01, 3.45560727e-01]]])

In [57]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [61]:
a = a.reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
a = np.array([1,2,3,4]).reshape(2,2)

In [65]:
a

array([[1, 2],
       [3, 4]])

In [66]:
a.diagonal()

array([1, 4])

In [73]:
arr = np.array([1,2,3,4,5])

In [74]:
arr.sum()

15

In [77]:
arr = np.array([8,5,3,2,11,100])

In [80]:
arr.argsort()

array([3, 2, 1, 0, 4, 5], dtype=int64)

In [81]:
arr.argmin()#will return the index of minimum value

3

In [82]:
arr.argmax()#will return the index of maximum value

5

In [83]:
arr

array([  8,   5,   3,   2,  11, 100])

In [84]:
arr.max()

100

In [85]:
arr.min()

2