In [67]:
import numpy as np,pandas as pd

In [68]:
data = {"Time":[0,1,2,3,4,1.5,2.5,5,8,12,15,24],"Marks":["Fail","Fail","Fail","Fail","Fail","Fail","Fail","Pass","Pass","Pass","Pass","Pass"]}

In [69]:
pd.DataFrame(data)

Time Marks
0    0.0  Fail
1    1.0  Fail
2    2.0  Fail
3    3.0  Fail
4    4.0  Fail
5    1.5  Fail
6    2.5  Fail
7    5.0  Pass
8    8.0  Pass
9   12.0  Pass
10  15.0  Pass
11  24.0  Pass

In [70]:
X = data['Time']
Y = data['Marks']

In [71]:
X = np.array(X)
Y = np.array(Y)

In [72]:
pd.unique(Y)

array(['Fail', 'Pass'], dtype=object)

In [73]:
from sklearn.preprocessing import LabelEncoder
encd = LabelEncoder()

Y = encd.fit_transform(Y)
pd.unique(Y)


array([0, 1], dtype=int64)

In [74]:
from sklearn.linear_model import LogisticRegression
logmod = LogisticRegression()

In [75]:
X = X.reshape(-1,1)
Y = Y.reshape(-1,1)

In [76]:
logmod.fit(X,Y)

C:\Users\SAHIL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\SAHIL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [77]:
intercept = logmod.intercept_

In [78]:
slope = logmod.coef_


In [79]:
prediction = logmod.predict(X)

In [87]:
Y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [89]:
prediction

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [93]:
acc = accuracy_score(Y,prediction)

In [91]:
from sklearn.metrics import tr

In [95]:
acc*100

100.0

In [96]:
from sklearn.metrics import confusion_matrix

In [97]:
met = confusion_matrix(Y,prediction)

In [98]:
met

array([[7, 0],
       [0, 5]], dtype=int64)