In [1]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

C:\Users\asus\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\asus\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
dataset = pd.read_csv('data/SaratogaHouses.csv')

In [8]:
X = dataset['livingArea'].values
y = dataset['price'].values

In [9]:
X.shape

(1728,)

In [10]:
# X = X.reshape(X.shape[0],1)
X = X.reshape(-1,1)

In [11]:
X[:10]

array([[ 906],
       [1953],
       [1944],
       [1944],
       [ 840],
       [1152],
       [2752],
       [1662],
       [1632],
       [1416]], dtype=int64)

In [12]:
reg = LinearRegression()
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [13]:
y_pred = reg.predict(X)

In [14]:
print(y[:10])
print(y_pred[:10])

[132500 181115 109000 155000  86060 120000 153000 170000  90000 122900]
[115928.4169181  234367.71823171 233349.61535509 233349.61535509
 108462.32915621 143756.56221241 324752.62916731 201449.05855429
 198055.38229888 173620.91325997]


In [15]:
reg.predict([[906]])

array([115928.4169181])

In [16]:
reg.coef_

array([113.12254185])

# Checking After Train Test Split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.20)

In [19]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1382, 1)
(1382,)
(346, 1)
(346,)


In [20]:
reg_2 = LinearRegression()
reg_2.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [21]:
y_pred = reg_2.predict(x_test)

In [22]:
from sklearn.metrics import mean_squared_error

In [23]:
mse = mean_squared_error(y_test, y_pred)

In [24]:
rmse = np.sqrt(mse)

In [25]:
print("Root Mean Squared Error",rmse)

Root Mean Squared Error 73149.75113957193


# Checking After Data Preprocessing

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
std = StandardScaler()
X = std.fit_transform(X)

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [28]:
X[:10]

array([[-1.36985441],
       [ 0.31951971],
       [ 0.30499787],
       [ 0.30499787],
       [-1.47634791],
       [-0.9729241 ],
       [ 1.60873645],
       [-0.1500198 ],
       [-0.19842594],
       [-0.54695011]])

In [30]:
y = y.reshape(-1,1)
y = std.fit_transform(y)

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [31]:
y[:10]

array([[-0.80748259],
       [-0.31349249],
       [-1.04627242],
       [-0.57885403],
       [-1.27937193],
       [-0.93449845],
       [-0.59917657],
       [-0.42643499],
       [-1.23933653],
       [-0.90503077]])

In [32]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.20)

In [33]:
reg_3 = LinearRegression()
reg_3.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [39]:
y_pred = reg_3.predict(x_test)

In [40]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

In [41]:
rmse

0.7262840113338039